return {
  require("plugins.treesitter"),
  require("plugins.lualine"),
  require("plugins.telescope"),
  require("plugins.catppuccin"),
  require("plugins.fidget"),
  require("plugins.project"),
  require("plugins.coc"),
  require("plugins.lspsaga"),
  require("plugins.nvim-tree"),
  require("plugins.mason"),
  "jiangmiao/auto-pairs",
  "lambdalisue/vim-suda",
  "norcalli/nvim-colorizer.lua",
}
