modules = [
    "┌──────────── \u001b[1mHardware Information\u001b[0m ────────────┐",

    "host",
    "cpu",
    "gpu",
    "displays",
    "memory",
   
    "|──────────── \u001b[1mSoftware Information\u001b[0m ────────────|",
  
    "os",
    "desktop",
    "shell",

    "|─────────────────── \u001b[1mUptime\u001b[0m ───────────────────|",
 
    "uptime",
    
    "└──────────────────────────────────────────────┘",
 
    "colors",
]

unknown_as_text = true

separator = "   "

color_margin = 1
color_character = ""
color_use_background = false

percentage_color_thresholds = [
    "75:brightgreen",
    "85:brightyellow",
    "90:brightred"
]

suppress_errors = true

[ascii]
display = true
colors = ["bright_magenta"]
side = "left"

[host]
title = "  󰌢"
format = "{host} ({chassis})"

[cpu]
title = "  "
format = "{name} ({core_count}c {thread_count}t) @ {max_clock_ghz} GHz"

[gpu]
title = "  "
ignore_disabled_gpus = true
# vram is not displayed https://github.com/LivacoNew/CrabFetch/issues/46
# format = "{vendor} {model} ({vram})"
format = "{vendor} {model}"

[displays]
title = "  󱄄"
key = "{width}x{height} @ {refresh_rate}Hz ({name})"
scale_size = true

[memory]
title = "  "
format = "{used} / {max} ({percent})"

[os]
title = "  "
format = "{distro} ({kernel})"

[desktop]
title = "  "
format = "{desktop} ({display_type})"

[shell]
title = "  "
format = "{name} {version}"

[uptime]
title = "  Uptime"
title_color = "magenta" 
